"""Specialist that asks Agent B (Google ADK) to build + deploy an invitation site."""

from __future__ import annotations

import json
import re
from datetime import datetime

from agent.db import fetch_one
from agent.llm.ai_model import llm
from agent.services.agent_b_client import generate_invitation
from agent.state.agent_state import AgentState
from agent.utils.progress import emit_progress


def _extract_event_id(task: str, preferred: int | None) -> int | None:
    if preferred:
        try:
            value = int(preferred)
            if value > 0:
                return value
        except (TypeError, ValueError):
            pass

    prompt = f"""
Extract the Gatherly event ID for an invitation-site request.

Return exactly one JSON object:
{{"event_id": 186}}

If none, return {{"event_id": null}}

User request:
{task}
"""
    raw = llm.invoke(prompt).text.strip()
    if raw.startswith("```"):
        raw = raw.removeprefix("```json").removeprefix("```").removesuffix("```").strip()
    try:
        parsed = json.loads(raw)
        event_id = parsed.get("event_id")
        if event_id is not None:
            event_id = int(event_id)
            if event_id > 0:
                return event_id
    except (json.JSONDecodeError, TypeError, ValueError, AttributeError):
        pass

    match = re.search(r"\bevent(?:\s+id)?\s*#?\s*(\d+)\b", task, flags=re.IGNORECASE)
    return int(match.group(1)) if match else None


def _fmt_dt(value) -> str:
    if value is None:
        return ""
    if isinstance(value, datetime):
        return value.strftime("%Y-%m-%d %H:%M")
    if hasattr(value, "isoformat"):
        return value.isoformat(sep=" ", timespec="minutes")
    return str(value)


def _load_event_payload(event_id: int) -> dict | None:
    row = fetch_one(
        """
        SELECT e.eventId, e.title, e.type, e.description, e.location,
               e.startsAt, e.status,
               c.fName AS clientFirstName, c.lName AS clientLastName,
               v.name AS venueName, v.address AS venueAddress, v.city AS venueCity
          FROM events e
     LEFT JOIN clients c ON c.clientId = e.clientId
     LEFT JOIN venues v ON v.venueId = e.venueId
         WHERE e.eventId = %s
        """,
        (event_id,),
    )
    if not row:
        return None

    client_name = " ".join(
        part for part in (row.get("clientFirstName"), row.get("clientLastName")) if part
    ).strip()
    venue_address = row.get("venueAddress") or row.get("venueCity") or row.get("location") or ""
    message = (row.get("description") or "").strip() or (
        f"You are invited to {row.get('title') or 'our celebration'}."
    )

    return {
        "event_id": int(row["eventId"]),
        "title": row.get("title") or f"Event {event_id}",
        "event_type": row.get("type") or "Event",
        "starts_at": _fmt_dt(row.get("startsAt")) or "TBA",
        "venue_name": row.get("venueName") or row.get("location") or "TBA",
        "venue_address": venue_address,
        "client_name": client_name or None,
        "message": message,
        "deploy": True,
        "include_router_pages": False,
    }


def _format_success(result: dict, event_id: int) -> str:
    lines = [
        f"Invitation site for event {event_id} was generated by Agent B.",
    ]
    deploy_url = result.get("deploy_url")
    deploy_status = result.get("deploy_status")
    if deploy_url:
        lines.append(f"Live URL: {deploy_url}")
    elif deploy_status == "skipped":
        lines.append(
            "Deploy skipped (set NETLIFY_TOKEN on Agent B to publish)."
        )
        if result.get("project_path"):
            lines.append(f"Local project: {result['project_path']}")
    elif deploy_status == "failed":
        lines.append(f"Deploy failed: {result.get('deploy_error') or 'unknown error'}")
        if result.get("project_path"):
            lines.append(f"Local project: {result['project_path']}")

    summary = (result.get("agent_summary") or "").strip()
    if summary:
        lines.append("")
        lines.append(summary[:1200])
    return "\n".join(lines)

async def _forward_agent_b_progress(event: dict) -> None:
    step = event.get("step") or "agent"

    tool = event.get("tool")
    message = event.get("message") or "Agent B is working"

    if tool:
        message = f"Agent B tool: {message}"

    await emit_progress(
        step=f"agent_b_{tool or step}",
        status=event.get("status") or "running",
        message=message,
        agent="invitation_site_agent",
    )


async def invitation_site_agent(state: AgentState) -> dict:
    task = state["remaining_task"] or state["message"]
    artifacts = dict(state.get("artifacts") or {})
    event_id = _extract_event_id(task, state.get("preferred_event_id"))

    if not event_id:
        response = (
            "Please specify the event ID to generate an invitation website "
            "(for example: create an invitation site for event 186)."
        )
    else:
        payload = _load_event_payload(event_id)
        if not payload:
            response = f"Event {event_id} was not found, so no invitation was generated."
        else:
            try:
                await emit_progress(
                    step="agent_b",
                    status="running",
                    message="Sending event information to Agent B",
                    agent="invitation_site_agent",
                )
                result = await generate_invitation(payload,on_progress=_forward_agent_b_progress,)
                await emit_progress(
                    step="agent_b",
                    status="completed",
                    message="Agent B finished the invitation website",
                    agent="invitation_site_agent",
                )
                artifacts["invitation"] = result
                response = _format_success(result, event_id)
            except Exception as error:
                response = (
                    f"Could not reach Agent B to generate the invitation for "
                    f"event {event_id}: {error}"
                )

    # Same return shape as other specialists so the graph stays consistent.
    return {
        "response": response,
        "selected_agent": "invitation_site_agent",
        "specialist_results": state["specialist_results"] + [response],
        "completed_agents": state["completed_agents"] + ["invitation_site_agent"],
        "remaining_task": "",
        "artifacts": artifacts,
    }
    